### ISSUE TITLE
Cannot get preview working in cms

### ISSUE THREAD

**Issue by tekstaker** [KenticoDevTrev/KenticoBoilerplate_v12#10]
I installed K12 using KIM and patched to .29.

I've installed the boilerplate and used the 'normal' instructions.

I've been through the instructions for preview mode, but I just see a blank page in the cmsdesk on the page tab - https://docs.kentico.com/k12sp/developing-websites/retrieving-content-in-mvc-applications/adding-preview-mode-support

Viewing the pages just on the mvc site seem to work fine.

admin: http://localhost/Kentico12_Boilerplate_Admin
mvc: http://localhost/Kentico12_Boilerplate

**Comment by KenticoDevTrev** [comment]
Shoot me an email and I can take a look to see if it's an issue with the boilerplate or your setup, others didn't have a problem with it but you never know! Devtrev.com/contact

**Comment by KenticoDevTrev** [comment]
Haven't heard back since, closing the issue.
