### ISSUE TITLE
KMVCHelper_GenericWidgetPageController Dependency Injection Support

### ISSUE THREAD

**Issue by kennyweigel** [KenticoDevTrev/KenticoBoilerplate_v12#6]

**Comment by KenticoDevTrev** [comment]
I assume this is a issue to convert the generic widget pages into using a di model?

**Comment by kennyweigel** [comment]
Yeah, just wondering if this was on your roadmap, or if you had a specific reason why you chose to implement it this way. I'm working on implementing something similar in a project I'm working on now.

**Comment by KenticoDevTrev** [comment]
It definitely can be integrated, I created that functionality beforei got my hands wet in di, my project site is using di now so I can definitely adjust it to use di, the routing is going to be revised come the service pack to integrate page templates, I'll add in di with it then, should only be a couple weeks, end of June is the service pack update

**Comment by kennyweigel** [comment]
Gotcha, I didn't know about the Kentico 12 SP, just updated a project this morning

**Comment by KenticoDevTrev** [comment]
I ended up removing the Generic Widget Page Controller, and stripped many of the stuff out of the master branch (still preserved on the BoilerplateVariants/Examples Branch). 

Installed AutoFac and implemented DI, although most helpers do not have this implemented yet.
