### ISSUE TITLE
EnvironmentHelper.GetUrl - Application path not removed correctly

### ISSUE THREAD

**Issue by KubaOczko** [KenticoDevTrev/KenticoBoilerplate_v12#8]
Relative URL starting with an application path is not removed because of wrong condition.

`if (ApplicationPath != "/" && string.IsNullOrWhiteSpace(ApplicationPath) && RelativeUrl.ToLower().IndexOf(ApplicationPath.ToLower()) == 0)`

Negation should be used prior `string.IsNullOrWhiteSpace(ApplicationPath)`

**Comment by KenticoDevTrev** [comment]
Fixed with Commit 1e32eadc579cfcf2a0e9353e08a30720c640128d
